
words_and_meanings = {
    "burbot": "A freshwater fish, taxonomic name Lota lota, which is similar to the ling and the cusk and spawns in the winter.",
    "spermatophytes": "Any plant that bears seeds rather than spores",
    "learnt": "To acquire, or attempt to acquire knowledge or an ability to do something.",
    "pistoling": "To shoot (at) a target with a pistol.",
    "amends": "(usually in the plural) An act of righting a wrong; compensation.",
    "rescission": "An act of rescinding: removing, taking away, or taking back.",
    "defends": "To ward off attacks against; to fight to protect; to guard.",
    "knucklers": "A knuckleball.",
    "injure": "To wound or cause physical harm to a living creature.",
    "inters": "To bury in a grave.",
    "nasalizes": "To speak through the nose.",
    "moodier": "Given to sudden or frequent changes of mind; temperamental.",
    "elastomers": "Any polymer having the elastic properties of rubber",
    "arrivistes": "An upstart or newcomer; nouveau riche; parvenu; an ambitious, brash or arrogant person who has yet to integrate with his or her new social group.",
    "unfroze": "To defrost something.",
    "triumvir": "One member of a triumvirate",
    "kabakas": "The title of the king of Buganda.",
    "dustmen": "A person employed to collect refuse from people's homes and take it to be processed.",
    "spindrift": "Sea spray blown from the tops of waves by the wind",
    "concessive": "(grammar) A phrase or clause that acts as a concession, such as \"even if\" or \"although\".",
    "despotisms": "Government by a singular authority, either a single person or tight-knit group, which rules with absolute power, especially in a cruel and oppressive way.",
    "agonising": "To writhe with agony; to suffer violent anguish.",
    "clangs": "A loud, ringing sound, like that made by free-hanging metal objects striking each other.",
    "swops": "To exchange or give (something) in an exchange (for something else).",
    "ascendants": "Being in control; superiority, or commanding influence; ascendency.",
    "practicability": "The state of being practicable; feasibility",
    "mitred": "Relating to an abbot's or bishop's mitre; wearing a mitre.",
    "ripened": "To grow ripe; to become mature (said of grain, fruit, flowers etc.)",
    "squalled": "To cry or wail loudly.",
    "indigenization": "The act of making something more native; transformation of some service, idea etc. to suit a local culture, especially through the use of more indigenous people in administration, employment etc.",
    "horsts": "An area of the earth's surface which is raised relative to surrounding land.",
    "threshers": "Anything or anyone that threshes.",
    "flocculent": "Diminutive of flocculent spiral galaxy",
    "destaining": "To remove a chemical stain from.",
    "humiliates": "To injure the dignity and self-respect of.",
    "catheters": "A small tube inserted into a body cavity to administer a drug, create an opening, distend a passageway, or remove fluid.",
    "streetlamp": "A lamp that illuminates a street or sidewalk.",
    "maze": "A labyrinth; a puzzle consisting of a complicated network of paths or passages, the aim of which is to find one's way.",
    "unfasten": "To detach from any connecting agency or link; to disconnect.",
    "organon": "A set of principles that are used in science or philosophy.",
    "platinizes": "To coat with platinum.",
    "gelatin": "A protein derived through partial hydrolysis of the collagen extracted from animal skin, bones, cartilage, ligaments, etc.",
    "agility": "The quality of being agile; the power of moving the limbs quickly and easily; quickness of motion",
    "sublimated": "To change state from a solid to a gas without passing through the liquid state.",
    "commences": "To begin, start.",
    "accesses": "A way or means of approaching or entering; an entrance; a passage.",
    "naltrexone": "An opiate antagonist used to treat opioid dependence",
    "contenting": "To give contentment or satisfaction; to satisfy; to make happy.",
    "tubercle": "A round nodule, small eminence, or warty outgrowth, especially those found on bones for the attachment of a muscle or ligament or small elevations on the surface of a tooth.",
    "catalogs": "A systematic list of names, books, pictures etc.",
    "gamays": "Any of several varieties of red grape used for making Beaujolais and other red wines.",
    "trotters": "In harness racing, a horse with a gait in which the front and back legs on opposite sides take a step together alternating with the other set of opposite legs; as opposed to a pacer.",
    "yuck": "Something disgusting.",
    "finest": "Senses referring to subjective quality.",
    "qualifies": "To describe or characterize something by listing its qualities.",
    "zinnia": "Any of several brightly coloured flowering plants, of the genus Zinnia, native to tropical America; old maid",
    "flaxseed": "The seed of the flax plant; a source of linseed oil.",
    "disenfranchised": "To deprive someone of a franchise, generally their right to vote",
    "cages": "An enclosure made of bars, normally to hold animals.",
    "opsonins": "Any chemical produced by the body, including antibodies and complement proteins, that causes a pathogen to be more susceptible to phagocytosis.",
    "gossipy": "Prone to gossip.",
    "bittiest": "Containing bits; fragmented.",
    "bushwah": "Nonsense.",
    "sickle": "An implement having a semicircular blade and short handle, used for cutting long grass and cereal crops.",
    "stimulate": "To encourage into action.",
    "affrighting": "To terrify, to frighten, to inspire fright in.",
    "sandiest": "Covered with sand.",
    "rattler": "Anything that rattles.",
    "intuitive": "One who has (especially parapsychological) intuition.",
    "intriguants": "An intriguer.",
    "topis": "An antelope of the species Damaliscus korrigum.",
    "handset": "The part of a landline telephone containing both receiver and transmitter (and sometimes dial), held in the hand.",
    "kittened": "To give birth to kittens.",
    "pulverizes": "To render into dust or powder.",
    "soapsuds": "Lather, suds, foam produced by soap in water.",
    "corydalises": "Any member of the genus Corydalis of annual and perennial herbaceous plants in the fumewort family.",
    "lockjaw": "A spasmodic, nervous system disease brought on by the tetanus bacteria. It causes muscles to seize up and may cause death by suffocation.",
    "condemn": "To strongly criticise or denounce; to excoriate the perpetrators of.",
    "equilibrate": "To balance, or bring into equilibrium.",
    "brigading": "To form or unite into a brigade; to group together.",
    "infuriates": "To make furious or mad with anger; to fill with fury.",
    "appreciator": "One who fully appreciates or understands a given thing.",
    "dyslexics": "A person who has dyslexia.",
    "gangstas": "A member of an urban criminal or street gang.",
    "delegating": "To authorize someone to be a delegate",
    "helicopter": "An aircraft that is borne along by one or more sets of long rotating blades which allow it to hover, move in any direction including reverse, or land; and typically having a smaller set of blades on its tail that stabilize the aircraft.",
    "grandee": "A high-ranking nobleman in Spain or Portugal.",
    "umlauted": "To place an umlaut over (a vowel).",
    "nystatin": "An antifungal drug used especially against Candida",
    "backlighted": "To illuminate something from behind.",
    "avocado": "The large, usually yellowish-green or black, pulpy fruit of the avocado tree.",
    "foggiest": "Obscured by mist or fog; unclear; hazy",
    "liquescent": "Melting.",
    "creeper": "A person or a thing that crawls or creeps.",
    "jazz": "A musical art form rooted in West African cultural and musical expression and in the African American blues tradition, with diverse influences over time, commonly characterized by blue notes, syncopation, swing, call and response, polyrhythms and improvisation.",
    "subcontractors": "A contractor hired by a general contractor employed by the contractor rather than directly hired by the customer.",
    "stationers": "A person or business that sells stationery.",
    "galliots": "A light galley.",
    "paced": "To walk back and forth in a small distance.",
    "traits": "An identifying characteristic, habit or trend.",
    "presidencies": "The office or role of president.",
    "apery": "A place where apes are kept.",
    "relocates": "To move (something) from one place to another.",
    "cooperate": "To work or act together, especially for a common purpose or benefit.",
    "audiobook": "A recording, usually made available for sale, of a reading of the full text or of an abridgement of a book.",
    "geometers": "A mathematician who specializes in geometry.",
    "junketeer": "A junketer.",
    "sums": "A type of administrative district used in China, Mongolia, and Russia. In Mongolia, a somon is smaller than a province. In China, it is only used in Inner Mongolia where it is equivalent to a township.",
    "gore": "Blood, especially that from a wound when thickened due to exposure to the air.",
    "deceptions": "An instance of actions and/or schemes fabricated to mislead someone into believing a lie or inaccuracy.",
    "livable": "Endurable, survivable, suitable for living in, inhabitable.",
    "hypnagogic": "That induces sleep; soporific, somniferous.",
    "knack": "A readiness in performance; aptness at doing something.",
    "sentinelling": "To watch over as a guard.",
    "nightgown": "A long loose robe worn mainly by women for sleeping in.",
    "policing": "To enforce the law and keep order among (a group).",
    "yarding": "To confine to a yard.",
    "prebooking": "To book in advance.",
    "horrific": "Horrifying, causing horror; horrible.",
    "steeled": "To edge, cover, or point with steel.",
    "daemon": "An evil supernatural spirit.",
    "doyen": "A commander in charge of ten men.",
    "vice": "A bad habit.",
    "grodiest": "Nasty, dirty, disgusting, foul, revolting, yucky, grotesque.",
    "mobilizations": "The act of mobilizing",
    "boon": "A prayer; petition.",
    "executant": "A person who executes a dance or piece of music; a performer.",
    "tedding": "To spread hay for drying.",
    "mitogen": "Any substance that stimulates mitosis",
    "coonhound": "Any of several American breeds of dog originally used in hunting raccoons.",
    "trivialises": "To make something appear trivial",
    "parallaxes": "An apparent shift in the position of two stationary objects relative to each other as viewed by an observer, due to a change in observer position.",
    "pomace": "The pulp that remains after a fruit has been pressed to extract the juice (or a nut, etc., has been pressed to extract the oil).",
    "marcel": "A hairstyle characterized by deep waves made by a curling iron.",
    "reissues": "Something that has issued, or been issued again.",
    "plonked": "To set or toss (something) down carelessly.",
    "productivity": "The state of being productive, fertile or efficient",
    "doubleheader": "A train with two engines (predates baseball term).",
    "blabbered": "To blather; to talk foolishly or incoherently.",
    "trickier": "Hard to deal with, complicated",
    "confederation": "A union or alliance of states or political organizations.",
    "evacuation": "The act of evacuating; leaving a place in an orderly fashion, especially for safety.",
    "spunky": "Spirited or plucky.",
    "boggiest": "Having the qualities of a bog; i.e. dank, squishy, muddy, and full of water and rotting vegetation.",
    "coauthored": "To write something in collaboration with another author.",
    "normalising": "To make normal, to make standard.",
    "exaggerate": "To overstate, to describe more than is fact.",
    "upbraided": "To criticize severely.",
    "encircle": "To surround, form a circle around.",
    "breezed": "(usually with along) To move casually, in a carefree manner.",
    "heptagon": "A polygon with seven sides and seven angles.",
    "ingredient": "One of the substances present in a mixture, especially food.",
    "surcease": "Cessation; stop; end.",
    "crowberries": "Empetrum; a small genus of dwarf evergreen shrubs that bear edible fruit.",
    "near": "The left side of a horse or of a team of horses pulling a carriage etc.",
    "concessions": "The act of conceding.",
    "reform": "The change of something that is defective, broken, inefficient or otherwise negative, in order to correct or improve it",
    "kappa": "The tenth letter of the Greek alphabet.",
    "stylized": "To represent in a particular style.",
    "shagged": "To make hairy or shaggy; to roughen.",
    "hydrometer": "An instrument that floats in a liquid and measures its specific gravity on a scale.",
    "dreamier": "As in a dream; resembling a dream.",
    "misogynists": "One who professes misogyny; a hater of women.",
    "presentative": "(grammar) A construct that serves to present something, or draw it to the attention of the interlocutor.",
    "defeasible": "Capable of being defeated, terminated, annulled, voided or invalidated.",
    "deckhouses": "A cabin that protrudes above a ship's deck.",
    "convoluting": "To make unnecessarily complex.",
    "hornbeams": "A tree of the genus Carpinus, having a smooth gray bark and a ridged trunk, the wood being white and very hard, common along the banks of streams in the United States.",
    "plaids": "A type of twilled woollen cloth, often with a tartan or chequered pattern.",
    "induline": "Any of a series of blue, bluish-red and black dyestuffs, formed by the interaction of para-amino azo compounds with primary monoamines in the presence of a small quantity of a mineral acid.",
    "capuchins": "A monk in the Order of Friars Minor Capuchin; (generally) a Franciscan.",
    "ohm": "In the International System of Units, the derived unit of electrical resistance; the electrical resistance of a device across which a potential difference of one volt causes a current of one ampere. Symbol: \u03a9",
    "strung": "To put (items) on a string.",
    "misrepresents": "To represent falsely; to inaccurately portray something.",
    "relaunch": "A subsequent launch.",
    "galleon": "A large, three masted, square rigged sailing ship with at least two decks.",
    "ton": "A unit of weight (mass) equal to 2240 pounds (a long ton) or 2000 pounds (a short ton) or 1000 kilograms (a metric ton).",
    "tapir": "Any one of the species of large odd-toed ungulates of the taxonomic family Tapiridae with a long prehensile upper lip, of which all four surviving species are in genus Tapirus.",
    "cartload": "The amount that a cart can carry.",
    "heliometer": "An astronomical instrument, based on a telescope, for measuring the diameter of the sun; now used to measure the angular distance between stars and other celestial bodies.",
    "regelate": "To undergo regelation.",
    "recks": "To make account of; to care for; to heed, regard, consider.",
    "zucchettos": "A small skullcap worn by Roman Catholic clergy (the Pope's is white, a cardinal's red, a bishop's purple, and a priest's black), Anglican clergy, and Syriac or Malankara Orthodox clergy",
    "paralyse": "To afflict with paralysis.",
    "stuccoes": "A plaster that is used to coat (interior or) exterior walls, or used for mouldings.",
    "permeability": "The property of being permeable",
    "disciple": "A person who learns from another, especially one who then teaches others.",
    "piglets": "A young pig",
    "confabulates": "To speak casually with; to chat.",
    "videocassettes": "A cassette containing blank or recorded videotape; either in VHS or Betamax format.",
    "fetich": "Something which is believed to possess, contain, or cause spiritual or magical powers; an amulet or a talisman.",
    "blushed": "To become red in the face (and sometimes experience an associated feeling of warmth), especially due to shyness, shame, excitement, or embarrassment.",
    "scientism": "The belief that the scientific method and the assumptions and research methods of the physical sciences are applicable to all other disciplines (such as the humanities and social sciences), or that those other disciplines are not as valuable.",
    "compeer": "The equal or peer of someone else; a close companion or associate.",
    "rhodolite": "A purplish-red garnet.",
    "paragraph": "A passage in text that is about a different subject from the preceding text, marked by commencing on a new line, the first line sometimes being indented.",
    "stooling": "To produce stool: to defecate.",
    "dojo": "The ring, made of compacted clay, in which a sumo wrestling match is held.",
    "fireguards": "A mesh screen around a fire to prevent sparks or falling embers.",
    "frugging": "The process whereby a product marketer falsely purports to be a market researcher conducting a statistical survey, when in reality the \"researcher\" is attempting to solicit a donation.",
    "megapixels": "One million pixels, used as a unit of resolution of digital cameras.",
    "identifier": "Someone who identifies; a person who establishes the identity of.",
    "buttonholing": "To detain (a person) in conversation against their will.",
    "nonviable": "Not viable: not capable of independent life; not practicable.",
    "tootsies": "A young woman",
    "inflames": "To set on fire; to kindle; to cause to burn, flame, or glow.",
    "reagent": "A compound or mixture of compounds used to treat or test materials, samples, other compounds or reactants in a laboratory or sometimes an industrial setting.",
    "tradesman": "A skilled manual worker (implied male).",
    "henges": "A prehistoric enclosure in the form of a circle or circular arc defined by a raised circular bank and a circular ditch usually running inside the bank, with one or more entrances leading into the enclosed open space.",
    "coatis": "Any of several omnivorous mammals, of the genus Nasua or Nasuella, in order Carnivora, that live in the range from southern United States to northern Argentina.",
    "longitudinal": "Any longitudinal piece, as in shipbuilding etc.",
    "clarions": "A medieval brass instrument, related to the trumpet, or its sound.",
    "coelacanth": "Either of two species of deep-water fish, Latimeria chalumnae of the Indian Ocean and Latimeria menadoensis of Indonesia.",
    "perorates": "To speak or declaim at great length, especially in a pompous or grandiloquent manner; to harangue.",
    "megabit": "106 = 1,000,000 bits or 125,000 bytes (125 kilobytes)",
    "spaceships": "A vehicle that flies through space.",
    "rille": "A long, narrow depression that resembles a channel, found on the surface of various lunar and planetary bodies.",
    "workpeople": "A worker; an employee.",
    "pasteurising": "To heat food for the purpose of killing harmful organisms such as bacteria, viruses, protozoa, molds, and yeasts.",
    "dietetic": "Relating to diet.",
    "gourdes": "The currency of Haiti, divided into 100 centimes.",
    "prototypes": "An original form or object which is a basis for other forms or objects (particularly manufactured items), or for its generalizations and models.",
    "figuratively": "(manner) In a figurative manner.",
    "estreated": "To extract or take out from the records of a court, and send up to the court of exchequer to be enforced; said of a forfeited recognizance.",
    "pragmatic": "A man of business.",
    "dewberries": "Small brambles of the genus Rubus which have stems that trail along the ground.",
    "absonant": "Discordant; harsh; contrary; unreasonable.",
    "aging": "To cause to grow old; to impart the characteristics of age to.",
    "mottles": "To mark with blotches of different color, or shades of color, as if stained; to spot; to maculate.",
    "drizzling": "To rain lightly.",
    "ejector": "One who, or that which, ejects or dispossesses.",
    "mollies": "Any of many New World fish of the genus Poecilia, formerly called Mollienesia.",
    "sundered": "To break or separate or to break apart, especially with force.",
    "parallelepipeds": "A solid figure, having six faces, all parallelograms; all opposite faces being similar and parallel.",
    "drainer": "That which drains.",
    "pharmacologic": "Of or having to do with pharmacology.",
    "viridian": "A bluish-green pigment made from chromium sesquioxide.",
    "entrances": "The action of entering, or going in.",
    "stripiest": "Having stripes; striped.",
    "entree": "(French Canada) A smaller dish served before the main course of a meal.",
    "gamecocks": "A fighting cock: a rooster used in cockfighting.",
    "interviewee": "Someone being interviewed, i.e. the person answering the questions.",
    "subgenres": "One of several categories within a particular genre.",
    "donning": "(clothing) To put on, to dress in.",
    "incoming": "The act of coming in; arrival.",
    "floweret": "A floret, or small or component flower",
    "acceding": "To approach; to arrive, to come forward.",
    "autosome": "Any chromosome other than sex chromosomes.",
    "phagocytosing": "To phagocytize; to ingest by phagocytosis.",
    "numen": "A divinity, especially a local or presiding god.",
    "caplets": "A smooth-coated tablet (pill, as in medicine) shaped like a capsule, used as a tamper-resistant alternative to a capsule, or an easy-to-swallow alternative to regular tablets.",
    "saline": "Water containing dissolved salt.",
    "quoined": "Furnished with a quoin.",
    "waveform": "The shape of a wave function represented by a graph showing some dependent variable as function of an independent variable.",
    "computerised": "Having undergone computerisation.",
    "incised": "To cut in or into with a sharp instrument; to carve; to engrave.",
    "grifters": "A con artist; someone who pulls confidence games.",
    "softback": "A softcover or paperback book.",
    "rigorously": "In a rigorous manner.",
    "convenor": "One who assembles people for an official or public purpose.",
    "hallucinating": "To seem to perceive things (with one or more of one's senses) which are not really present; to have visions; to experience a hallucination.",
    "sangria": "A cold drink, originating in Spain, consisting of red or white wine, brandy or sherry, fruit juice, sugar and soda water and garnished with orange and other fruit.",
    "fops": "A vain man; a dandy.",
    "nanosecond": "A measure of time equal to one billionth of a second. Abbreviation: ns",
    "weirding": "To destine; doom; change by witchcraft or sorcery.",
    "tropopause": "The zone of transition between the troposphere and the stratosphere (approximately 13 kilometers). The tropopause normally occurs at an altitude of between 25,000 and 45,000 feet in polar and temperate zones. It occurs at 55,000 feet in the tropics.",
    "deregulated": "To remove the regulations, or legal restrictions, from.",
    "gracile": "Lean, slender, thin.",
    "missionaries": "One who is sent on a mission.",
    "fundamentalist": "One who reduces religion to strict interpretation of core or original texts.",
    "wailed": "To cry out, as in sorrow or anguish.",
    "collectivize": "To organize a farm or industrial enterprise on the basis of collective control",
    "announcers": "One who makes announcements.",
    "flugelhorn": "A brass instrument resembling a cornet but with a wider, conical bore, and usually with three valves, in the same B-flat pitch as many trumpets and cornets but with a more deeply conical mouthpiece than those. A bugle with valves.",
    "bandsaws": "A powered saw whose blade is a continuous band of metal with teeth along one edge.",
    "madcaps": "An impulsive, hasty, capricious person.",
    "sued": "To file a legal action against someone, generally a non-criminal action.",
    "amentia": "Mental impairment; state of being mentally handicapped."
}
